TITLE    = Another RDF Encoding Form (aREF)
AUTHOR   = Jakob Voß (VZG)
DATE     = SWIB2013 Lightning Talk, 2013-11-27
VERSION  = none
LANGUAGE = english

include ../vzgspec/Makefile

# TODO: simplify creation of slides - put into local.make?
TEX_TEMPLATE = ../vzgspec/templates/vzg-slides.latex
TEX_ARGS     += --slide-level 2 $(TOC) -t beamer 
TEX_VARS     = -V documentclass=beamer
